```bash
#!/bin/bash

# ============================================================
# 07_featurecounts_read_counting.sh
# Gene-level read counting using featureCounts
# ============================================================
# This script was adapted from the RNA-seq analysis workflow provided by
# Prof. Dr. Emre Yörük and reorganized for this thesis project.
# ============================================================

# Installation
# conda install -c bioconda subread

# Create folders
mkdir -p bams

# Notes:
# - Place the GTF annotation file in the main project directory.
# - Place STAR-generated sorted BAM files into the bams/ folder.
# - BAM files should be the output files generated by STAR:
#   sample_Aligned.sortedByCoord.out.bam

# Gene-level read counting with featureCounts
# Since paired-end reads were used, -p and --countReadPairs options were included.

featureCounts \
-a Oryza_sativa.IRGSP-1.0.59.gtf \
-o count.out \
-T 11 \
-p \
--countReadPairs \
bams/*.bam

# Output files:
# count.out         : gene-level count table
# count.out.summary : assignment summary for each BAM file

# Parameter explanation:
# -a               : GTF annotation file
# -o               : output count table
# -T 4             : number of threads
# -p               : indicates paired-end reads
# --countReadPairs : counts read pairs instead of individual reads
# bams/*.bam       : input STAR-aligned BAM files
```
